default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &development
  <<: *default
  database: tatame_development
  username: postgres
  password: tatame
  host: localhost

test:
  <<: *development
  database: tatame_test

production:
  url: <%= ENV['TATAME_DATABASE_URL'] %>